# CI Config

stages:
  - build
  - deploy

# Build the hugo theme and generate the static site
build_static:
  variables:
    HUGO_ENV: "production"
  stage: build
  artifacts:
    name: "build_static_${CI_BUILD_REF}"
    expire_in: 1d
    paths:
      - public
  image: monachus/hugo
  script:
    - curl -sL https://deb.nodesource.com/setup_8.x | bash -
    - apt-get install -y nodejs build-essential
    - cd ./themes/andrewpwarren/src
    - npm install
    - npm run build:production
    - cd ../../../
    - hugo

# Deploy to Production(S3)
deploy_prod:
  stage: deploy
  image: node:latest
  only:
    - master
  dependencies: 
    - build_static
  script:
    - npm install -g s3-deploy
    - s3-deploy './public/**' --cwd './public/' --region ${AWS_REGION} --bucket ${AWS_S3_BUCKET_NAME} --invalidate --deleteRemoved
